#!/bin/sh

TEXNAME=$1.tex

#compilation version etudiante
LC_CTYPE=C && LANG=C && sed '/setboolean{sol}/ s/true/false/' $TEXNAME > etudiant.tex
pdflatex etudiant.tex
pdflatex etudiant.tex
mv etudiant.pdf $1_etu.pdf

#compilation version enseignant
sed '/setboolean{sol}/ s/false/true/' $TEXNAME > enseignant.tex
pdflatex enseignant.tex
pdflatex enseignant.tex
mv enseignant.pdf $1_ens.pdf
